### ISSUE TITLE
Error loading script: infinity_grid.py. An update to the issue.

### ISSUE THREAD

**Issue by blu3nh** [mcmonkeyprojects/sd-infinity-grid-generator-script#134] opened 2024-04-09 16:12 UTC
Update to this error saga:
https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/issues/132

```python
*** Error loading script: infinity_grid.py
    Traceback (most recent call last):
      File "B:\A1111\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "B:\A1111\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "B:\A1111\extensions\sd-infinity-grid-generator-script\scripts\infinity_grid.py", line 22, in <module>
        import gridgencore as core
      File "B:\A1111\extensions\sd-infinity-grid-generator-script\gridgencore.py", line 256, in <module>
        YamlIncludeConstructor.add_to_loader_class(loader_class=GridYamlLoader, base_dir=ASSET_DIR)
    AttributeError: type object 'Constructor' has no attribute 'add_to_loader_class'

---
```

Updated A1111, updated the infinity script extension, deleted and recreated venv.
Error still persists x_x

````python
try:
    from yamlinclude import YamlIncludeConstructor
except:
    from yaml_include import Constructor as YamlIncludeConstructor
````
^ this code is already present, but only changed the error :/

**Comment by mcmonkey4eva** [comment] 2024-04-09 19:13
duplicate of #133

**Closed by mcmonkey4eva** 2024-04-09 19:13 UTC
